---
kind: wireguard/v1
metadata:
  name: wg0
spec:
  address: 100.96.0.1/24
  port: 51820
  privatekey: "privateKeyValue"
  publickey: "publicKeyValue"
  peers:
    - publickey: "peerPublicKey"
      allowedips:
        - 100.96.0.2/32
