---
kind: wireguard/v1
metadata:
  name: wg0
spec:
  socket:
    protocol: udp
    address: 0.0.0.0
    port: 51820
  privateKey: "privateKey111"
  peers:
    - name: peer1
      publicKey: "publicKey1"
---
kind: squid/v1
metadata:
  name: squid
spec:
  socket:
    protocol: tcp
    address: 0.0.0.0
    port: 3128
  access: "allow all"
