FROM golang:1.22.1-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    dpkg-dev \
    gettext-base \
    git \
    iproute2 \
    iptables \
    make \
    shellcheck \
    wireguard-tools
