FROM debian:12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    curl \
    dpkg-dev \
    git \
    iproute2 \
    iptables \
    make \
    shellcheck \
    wireguard-tools
