name: Packer - Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse version
        id: version
        run: |
          echo "VERSION=$(VERSION=${GITHUB_REF#refs/tags/v}; echo ${VERSION%%-*})" >> "$GITHUB_OUTPUT"
          if [[ $GITHUB_REF == refs/tags/v*-* ]]; then
            echo "REVISION=$(REVISION=${GITHUB_REF#refs/tags/v}; echo ${REVISION#*-})" >> "$GITHUB_OUTPUT"
          else
            echo "REVISION=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        run: make build-amd64 VERSION=${{ steps.version.outputs.VERSION }} REVISION=${{ steps.version.outputs.REVISION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            *.deb
            SHA256SUMS

  release:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
      - name: Check if pre-release
        id: prerelease
        run: |
          echo "PRERELEASE=$(if [[ "${{ github.ref }}" == *"rc"* ]]; then echo "true"; else echo "false"; fi)" >> "$GITHUB_OUTPUT"

      - uses: actions/download-artifact@v4
        with:
          name: package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.prerelease.outputs.PRERELEASE }}
          generate_release_notes: true
          files: |
            *.deb
            SHA256SUMS
