name: Packer - Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test
        run: make test

  build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse version (remove the 'v' prefix and revision with a dash)
        id: version
        run: echo ::set-output name=VERSION::${${GITHUB_REF#refs/tags/v}%-*}

      - name: Parse revision
        id: revision
        run: echo ::set-output name=REVISION::${GITHUB_REF#refs/tags/v*-}

      - name: Build
        run: make build
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            dist/*.deb
