name: Packer - Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test
        run: make test

  build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse version
        id: version
        run: |
          echo "VERSION=$(VERSION=${GITHUB_REF#refs/tags/v}; echo ${VERSION%%-*})" >> "$GITHUB_OUTPUT"
          if [[ $GITHUB_REF == refs/tags/v*-* ]]; then
            echo "REVISION=$(REVISION=${GITHUB_REF#refs/tags/v}; echo ${REVISION#*-})" >> "$GITHUB_OUTPUT"
          else
            echo "REVISION=1" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        run: make build VERSION=${{ steps.version.outputs.VERSION }} REVISION=${{ steps.version.outputs.REVISION }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            dist/*.deb
