name: Packer - Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        run: make lint

  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: make test

  build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: make build
        env:
          VERSION: ${{ github.ref }}
          REVISION: 1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            dist/*.deb
